require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TrucksController do

  def mock_truck(stubs={})
    @mock_truck ||= mock_model(Truck, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all trucks as @trucks" do
      Truck.stub(:all) { [mock_truck] }
      get :index
      assigns(:trucks).should eq([mock_truck])
    end
  end

  describe "GET show" do
    it "assigns the requested truck as @truck" do
      Truck.stub(:find).with("37") { mock_truck }
      get :show, :id => "37"
      assigns(:truck).should be(mock_truck)
    end
  end

  describe "GET new" do
    it "assigns a new truck as @truck" do
      Truck.stub(:new) { mock_truck }
      get :new
      assigns(:truck).should be(mock_truck)
    end
  end

  describe "GET edit" do
    it "assigns the requested truck as @truck" do
      Truck.stub(:find).with("37") { mock_truck }
      get :edit, :id => "37"
      assigns(:truck).should be(mock_truck)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created truck as @truck" do
        Truck.stub(:new).with({'these' => 'params'}) { mock_truck(:save => true) }
        post :create, :truck => {'these' => 'params'}
        assigns(:truck).should be(mock_truck)
      end

      it "redirects to the created truck" do
        Truck.stub(:new) { mock_truck(:save => true) }
        post :create, :truck => {}
        response.should redirect_to(truck_url(mock_truck))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved truck as @truck" do
        Truck.stub(:new).with({'these' => 'params'}) { mock_truck(:save => false) }
        post :create, :truck => {'these' => 'params'}
        assigns(:truck).should be(mock_truck)
      end

      it "re-renders the 'new' template" do
        Truck.stub(:new) { mock_truck(:save => false) }
        post :create, :truck => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested truck" do
        Truck.stub(:find).with("37") { mock_truck }
        mock_truck.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :truck => {'these' => 'params'}
      end

      it "assigns the requested truck as @truck" do
        Truck.stub(:find) { mock_truck(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:truck).should be(mock_truck)
      end

      it "redirects to the truck" do
        Truck.stub(:find) { mock_truck(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(truck_url(mock_truck))
      end
    end

    describe "with invalid params" do
      it "assigns the truck as @truck" do
        Truck.stub(:find) { mock_truck(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:truck).should be(mock_truck)
      end

      it "re-renders the 'edit' template" do
        Truck.stub(:find) { mock_truck(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested truck" do
      Truck.stub(:find).with("37") { mock_truck }
      mock_truck.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the trucks list" do
      Truck.stub(:find) { mock_truck }
      delete :destroy, :id => "1"
      response.should redirect_to(trucks_url)
    end
  end

end
